### PR TITLE
Fix composer.json

### PR DESCRIPTION
**Pull request by maaxca**
Hello,

having a "symfony/symfony": "2.8.*" dependency, it was impossible to me to install your bundle even if it allows framework starting at 2.3, due to the "symfony/console": "~3.1" dependency.

### CODE REVIEW

**Comment by andythorne** [comment]
Thanks @maaxca, please rebase your PR and I'll get it merged in!

**Comment by maaxca** [comment]
@andythorne : Thanks! I may be have other PR todo.. Do you prefer I open issue first ? Do you have issue on your side that you may be can share in order to work together on ?

**Comment by andythorne** [comment]
Please feel free to open an issue, if there's something you would like help with please let me know :)

**Comment by maaxca** [comment]
Ok, I'll do... We stay in touch ;-) thanks

**Pull request merged**
